FROM node:20

ENV NODE_ENV=$NODE_ENV
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV DB_SYNC=$DB_SYNC
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV JWT_KEY=$JWT_KEY
ENV JWT_EXPIRES_IN=$JWT_EXPIRES_IN
ENV API_DOCS_USER=$API_DOCS_USER
ENV API_DOCS_PASSWORD=$API_DOCS_PASSWORD
ENV GOOGLE_SEARCH_API_KEY=$GOOGLE_SEARCH_API_KEY
ENV GOOGLE_SEARCH_ENGINE_ID=$GOOGLE_SEARCH_ENGINE_ID
ENV SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
ENV SENTRY_DSN=$SENTRY_DSN

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY ./dist ./src

COPY ./views ./views

COPY ./public ./public

EXPOSE 3000

CMD ["node", "src/main.js"]